_target_: finetune.sft.models.sft_base_model.TrainableReasoningVLA.from_alpamayo_checkpoint
checkpoint_path: /data/mnt_m181/z59900495/workspace/model/Alpamayo-1.5-10B
vlm_name_or_path: /data/mnt_m181/z59900495/workspace/model/Qwen3-VL-8B-Instruct # Qwen/Qwen3-VL-8B-Instruct